# Generated by Django 5.0.9 on 2024-11-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_id_alter_car_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
